import * as vscode from 'vscode';

const GCC_CLANG_TEMPLATE = '${compiler} ${standard} -fdiagnostics-color=always ${modeOptions} ${warnings_options} ${defines} ${sanitizers_options} ${file} ${linked} -o ${out}';
const MSVC_TEMPLATE = '${compiler} ${standard} ${modeOptions} ${warnings_options} ${defines} ${sanitizers_options} ${linked} /Fe:${out} ${file}';

export const CONFIG_SECTION = 'cpp-runner-pro';
export const cfg = vscode.workspace.getConfiguration(CONFIG_SECTION);

// 在 package.json 中定义了default值, 如果用户没有配置，返回 default 值; 如果配置文件损坏，返回 default 值;永远不会返回 undefined

// 用户的配置文件可能是非法的, 比如需要一个array值, 配置文件中可能是string值, 此时会出错
// 并未做类型检查, 假设用户配置是合法的

/** @readonly Use setOutputDirectory() to modify */
export let outputDirectory: string = cfg.get<string>('outputDirectory')!;
/** @readonly Use setWorkspaceCompiler() to modify */
export let compiler: string = cfg.get<string>('compiler')!;
/** @readonly Use setWorkspaceBuildMode() to modify */
export let buildMode: string = cfg.get<string>('buildMode')!;
/** @readonly Use setWorkspaceCppStandard() to modify */
export let cppStandard: string = cfg.get<string>('standard')!;
/** @readonly Use setTreatWarningsAsErrors() to modify */
export let treatWarningsAsErrors: boolean = cfg.get<boolean>('treatWarningsAsErrors')!;
/** @readonly Use setExcludedFileExtensions() to modify */
export let excludedFileExtensions: string[] = cfg.get<string[]>('excludedFileExtensions')!;
/** @readonly Use setThemeColor() to modify */
export let themeColor: string = cfg.get<string>('themeColor')!;

/** @readonly Use setToolchainPath() to modify */
export let gppPath: string = cfg.get<string>('gcc.path')!;
/** @readonly Use setBuildModeOptions() to modify */
export let gccDebugOptions: string[] = cfg.get<string[]>('gcc.debug_options')!;
/** @readonly Use setBuildModeOptions() to modify */
export let gccReleaseOptions: string[] = cfg.get<string[]>('gcc.release_options')!;
/** @readonly Use setToolchainWarningsOptions() to modify */
export let gccWarningsOptions: string[] = cfg.get<string[]>('gcc.warnings_options')!;
/** @readonly Use setToolchainSanitizers() to modify */
export let gccSanitizersOptions: string[] = cfg.get<string[]>('gcc.sanitizers_options')!;

/** @readonly Use setToolchainPath() to modify */
export let clangppPath: string = cfg.get<string>('clang.path')!;
/** @readonly Use setBuildModeOptions() to modify */
export let clangDebugOptions: string[] = cfg.get<string[]>('clang.debug_options')!;
/** @readonly Use setBuildModeOptions() to modify */
export let clangReleaseOptions: string[] = cfg.get<string[]>('clang.release_options')!;
/** @readonly Use setToolchainWarningsOptions() to modify */
export let clangWarningsOptions: string[] = cfg.get<string[]>('clang.warnings_options')!;
/** @readonly Use setToolchainSanitizers() to modify */
export let clangSanitizersOptions: string[] = cfg.get<string[]>('clang.sanitizers_options')!;

/** @readonly Use setToolchainPath() to modify */
export let msvcPath: string = cfg.get<string>('msvc.path')!;
/** @readonly Use setBuildModeOptions() to modify */
export let msvcDebugOptions: string[] = cfg.get<string[]>('msvc.debug_options')!;
/** @readonly Use setBuildModeOptions() to modify */
export let msvcReleaseOptions: string[] = cfg.get<string[]>('msvc.release_options')!;
/** @readonly Use setToolchainWarningsOptions() to modify */
export let msvcWarningsOptions: string[] = cfg.get<string[]>('msvc.warnings_options')!;
/** @readonly Use setToolchainSanitizers() to modify */
export let msvcSanitizersOptions: string[] = cfg.get<string[]>('msvc.sanitizers_options')!;

/** @readonly Modify via VS Code configuration */
export let defines: string[] = cfg.get<string[]>('defines')!;
/** @readonly Modify via VS Code configuration */
export let linked_libraries: string[] = cfg.get<string[]>('linked_libraries')!;
/** @readonly Modify via VS Code configuration */
export let programArgs: string[] = cfg.get<string[]>('programArgs')!;

// cfg.inspect().globalValue 只返回用户明确设置的全局值, 不会返回默认值. 如果用户没设置过,就是 undefined
/** @readonly Use setGlobalCompiler() to modify */
export let globalCompiler: string = (cfg.inspect<string>('compiler')?.globalValue ?? cfg.get<string>('compiler'))!;
/** @readonly Use setGlobalBuildMode() to modify */
export let globalBuildMode: string = (cfg.inspect<string>('buildMode')?.globalValue ?? cfg.get<string>('buildMode'))!;
/** @readonly Use setGlobalCppStandard() to modify */
export let globalCppStandard: string = (cfg.inspect<string>('standard')?.globalValue ?? cfg.get<string>('standard'))!;

/** @readonly Generated by buildCompileCommand() */
export let compileCmd: string = '';

let standardOption = compiler === 'msvc' ? `/std:${cppStandard}` : `-std=${cppStandard}`;

// 监听配置变化,自动同步更新变量
export function onConfigChange(event: vscode.ConfigurationChangeEvent): void
{
    if (!event.affectsConfiguration(CONFIG_SECTION)) { return; }

    const freshCfg = vscode.workspace.getConfiguration(CONFIG_SECTION);

    // 项目级配置
    if (event.affectsConfiguration(`${CONFIG_SECTION}.defines`))
    {
        defines = freshCfg.get<string[]>('defines')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.linked_libraries`))
    {
        linked_libraries = freshCfg.get<string[]>('linked_libraries')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.programArgs`))
    {
        programArgs = freshCfg.get<string[]>('programArgs')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.compiler`))
    {
        compiler = freshCfg.get<string>('compiler')!;
        standardOption = compiler === 'msvc' ? `/std:${cppStandard}` : `-std=${cppStandard}`;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.buildMode`))
    {
        buildMode = freshCfg.get<string>('buildMode')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.standard`))
    {
        cppStandard = freshCfg.get<string>('standard')!;
        standardOption = compiler === 'msvc' ? `/std:${cppStandard}` : `-std=${cppStandard}`;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.outputDirectory`))
    {
        outputDirectory = freshCfg.get<string>('outputDirectory')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.treatWarningsAsErrors`))
    {
        treatWarningsAsErrors = freshCfg.get<boolean>('treatWarningsAsErrors')!;
    }

    // Toolchain configs
    if (event.affectsConfiguration(`${CONFIG_SECTION}.gcc`))
    {
        gppPath = freshCfg.get<string>('gcc.path')!;
        gccDebugOptions = freshCfg.get<string[]>('gcc.debug_options')!;
        gccReleaseOptions = freshCfg.get<string[]>('gcc.release_options')!;
        gccWarningsOptions = freshCfg.get<string[]>('gcc.warnings_options')!;
        gccSanitizersOptions = freshCfg.get<string[]>('gcc.sanitizers_options')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.clang`))
    {
        clangppPath = freshCfg.get<string>('clang.path')!;
        clangDebugOptions = freshCfg.get<string[]>('clang.debug_options')!;
        clangReleaseOptions = freshCfg.get<string[]>('clang.release_options')!;
        clangWarningsOptions = freshCfg.get<string[]>('clang.warnings_options')!;
        clangSanitizersOptions = freshCfg.get<string[]>('clang.sanitizers_options')!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.msvc`))
    {
        msvcPath = freshCfg.get<string>('msvc.path')!;
        msvcDebugOptions = freshCfg.get<string[]>('msvc.debug_options')!;
        msvcReleaseOptions = freshCfg.get<string[]>('msvc.release_options')!;
        msvcWarningsOptions = freshCfg.get<string[]>('msvc.warnings_options')!;
        msvcSanitizersOptions = freshCfg.get<string[]>('msvc.sanitizers_options')!;
    }

    // Global configs
    if (event.affectsConfiguration(`${CONFIG_SECTION}.compiler`))
    {
        globalCompiler = (freshCfg.inspect<string>('compiler')?.globalValue ?? freshCfg.get<string>('compiler'))!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.buildMode`))
    {
        globalBuildMode = (freshCfg.inspect<string>('buildMode')?.globalValue ?? freshCfg.get<string>('buildMode'))!;
    }
    if (event.affectsConfiguration(`${CONFIG_SECTION}.standard`))
    {
        globalCppStandard = (freshCfg.inspect<string>('standard')?.globalValue ?? freshCfg.get<string>('standard'))!;
    }

    // Rebuild compile command template after any config change
    buildCompileCommand();
}

export async function setWorkspaceCompiler(value: string): Promise<void>
{
    compiler = value;
    standardOption = compiler === 'msvc' ? `/std:${cppStandard}` : `-std=${cppStandard}`;
    await cfg.update('compiler', value, vscode.ConfigurationTarget.Workspace);
}

export async function setGlobalCompiler(value: string): Promise<void>
{
    globalCompiler = value;
    await cfg.update('compiler', value, vscode.ConfigurationTarget.Global);
}

export async function setWorkspaceBuildMode(value: string): Promise<void>
{
    buildMode = value;
    await cfg.update('buildMode', value, vscode.ConfigurationTarget.Workspace);
}

export async function setGlobalBuildMode(value: string): Promise<void>
{
    globalBuildMode = value;
    await cfg.update('buildMode', value, vscode.ConfigurationTarget.Global);
}

export async function setWorkspaceCppStandard(value: string): Promise<void>
{
    cppStandard = value;
    standardOption = compiler === 'msvc' ? `/std:${cppStandard}` : `-std=${cppStandard}`;
    await cfg.update('standard', value, vscode.ConfigurationTarget.Workspace);
}

export async function setGlobalCppStandard(value: string): Promise<void>
{
    globalCppStandard = value;
    await cfg.update('standard', value, vscode.ConfigurationTarget.Global);
}

export async function setOutputDirectory(value: string): Promise<void>
{
    outputDirectory = value;
    await cfg.update('outputDirectory', value, vscode.ConfigurationTarget.Workspace);
}

export async function setTreatWarningsAsErrors(value: boolean): Promise<void>
{
    treatWarningsAsErrors = value;
    await cfg.update('treatWarningsAsErrors', value, vscode.ConfigurationTarget.Workspace);
}

export async function setExcludedFileExtensions(values: string[]): Promise<void>
{
    excludedFileExtensions = values;
    await cfg.update('excludedFileExtensions', values, vscode.ConfigurationTarget.Workspace);
}

export async function setThemeColor(value: string): Promise<void>
{
    themeColor = value;
    await cfg.update('themeColor', value, vscode.ConfigurationTarget.Global);
}

function getToolchainConfig(comp: string): { path: string; debug_options: string[]; release_options: string[]; warnings_options: string[]; sanitizers_options: string[] }
{
    if (comp === 'gcc') { return { path: gppPath, debug_options: gccDebugOptions, release_options: gccReleaseOptions, warnings_options: gccWarningsOptions, sanitizers_options: gccSanitizersOptions }; }
    if (comp === 'clang') { return { path: clangppPath, debug_options: clangDebugOptions, release_options: clangReleaseOptions, warnings_options: clangWarningsOptions, sanitizers_options: clangSanitizersOptions }; }
    if (comp === 'msvc') { return { path: msvcPath, debug_options: msvcDebugOptions, release_options: msvcReleaseOptions, warnings_options: msvcWarningsOptions, sanitizers_options: msvcSanitizersOptions }; }
    return { path: '', debug_options: [], release_options: [], warnings_options: [], sanitizers_options: [] };
}

async function saveToolchain(comp: string): Promise<void>
{
    await cfg.update(comp, getToolchainConfig(comp), vscode.ConfigurationTarget.Workspace);
}

export async function setBuildModeOptions(comp: string, mode: string, options: string[]): Promise<void>
{
    if (comp === 'gcc') { if (mode === 'debug') { gccDebugOptions = options; } else { gccReleaseOptions = options; } }
    if (comp === 'clang') { if (mode === 'debug') { clangDebugOptions = options; } else { clangReleaseOptions = options; } }
    if (comp === 'msvc') { if (mode === 'debug') { msvcDebugOptions = options; } else { msvcReleaseOptions = options; } }
    await saveToolchain(comp);
}

export async function setToolchainPath(comp: string, value: string): Promise<void>
{
    if (comp === 'gcc') { gppPath = value; }
    if (comp === 'clang') { clangppPath = value; }
    if (comp === 'msvc') { msvcPath = value; }
    await saveToolchain(comp);
}

export async function setToolchainWarningsOptions(comp: string, value: string[]): Promise<void>
{
    if (comp === 'gcc') { gccWarningsOptions = value; }
    if (comp === 'clang') { clangWarningsOptions = value; }
    if (comp === 'msvc') { msvcWarningsOptions = value; }
    await saveToolchain(comp);
}

export async function setToolchainSanitizers(comp: string, values: string[]): Promise<void>
{
    if (comp === 'gcc') { gccSanitizersOptions = values; }
    if (comp === 'clang') { clangSanitizersOptions = values; }
    if (comp === 'msvc') { msvcSanitizersOptions = values; }
    await saveToolchain(comp);
}

export async function updateDefines(values: string[]): Promise<void>
{
    defines = values;
    await cfg.update('defines', values, vscode.ConfigurationTarget.Workspace);
}

export async function updateLinkedLibraries(values: string[]): Promise<void>
{
    linked_libraries = values;
    await cfg.update('linked_libraries', values, vscode.ConfigurationTarget.Workspace);
}

export async function updateProgramArgs(values: string[]): Promise<void>
{
    programArgs = values;
    await cfg.update('programArgs', values, vscode.ConfigurationTarget.Workspace);
}

export async function updateSetting(key: string, value: any, scope: 'global' | 'workspace' | 'workspaceFolder' = 'workspace'): Promise<void>
{
    if (key === 'compiler') { compiler = value; }
    if (key === 'buildMode') { buildMode = value; }
    if (key === 'standard') { cppStandard = value; }
    if (key === 'compiler' || key === 'standard') { standardOption = compiler === 'msvc' ? `/std:${cppStandard}` : `-std=${cppStandard}`; }
    if (key === 'outputDirectory') { outputDirectory = value; }
    const target = scope === 'global' ? vscode.ConfigurationTarget.Global : scope === 'workspaceFolder' ? vscode.ConfigurationTarget.WorkspaceFolder : vscode.ConfigurationTarget.Workspace;
    await cfg.update(key, value, target);
}

export function buildCompileCommand(): void
{
    const isMSVC = compiler === 'msvc';
    const toolchain = getToolchainConfig(compiler);

    const modeOptions = (buildMode === 'debug' ? toolchain.debug_options : toolchain.release_options).join(' ');
    const definesStr = defines.length ? defines.map(v => isMSVC ? `/D${v}` : `-D${v}`).join(' ') : '';
    const linkerStr = linked_libraries.length ? linked_libraries.map(v => isMSVC ? `${v}.lib` : `-l${v}`).join(' ') : '';

    let sanitizersOptions = '';
    if (!isMSVC && buildMode === 'debug')
    {
        const list = Array.isArray(toolchain.sanitizers_options) ? toolchain.sanitizers_options as string[] : [];
        if (list.length)
        {
            sanitizersOptions = `-fsanitize=${list.join(',')} -fno-omit-frame-pointer -g`;
        }
    }

    const TEMPLATE = isMSVC ? MSVC_TEMPLATE : GCC_CLANG_TEMPLATE;

    compileCmd = TEMPLATE
        .replace('${compiler}', toolchain.path)
        .replace('${standard}', standardOption)
        .replace('${modeOptions}', modeOptions)
        .replace('${warnings_options}', (toolchain.warnings_options || []).join(' '))
        .replace('${defines}', definesStr)
        .replace('${sanitizers_options}', sanitizersOptions)
        .replace('${linked}', linkerStr)
        .replace(/\s+/g, ' ')
        .trim();
}

// Initialize compile command template on module load
buildCompileCommand();
